server:
  port: 8080

spring:
  cloud:
    stream:
      function:
        productEventProducer
      bindings:
        productEventProducer-out-0:
          destination: product-event-1
          # Here, we extract the key which is injected into PartitionSelectorStrategy#selectPartition
#          producer:
#            partitionKeyExpression: 'getHeaders().get("partitionKey")'
#            partitionCount: 5

    ############ In case of you want to enter your configuration ##########
#  kafka:
#    bootstrap-servers: YOUR_SERVER_URL
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: SCRAM-SHA-256
#        jaas:
#          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="YOUR_USERNAME" password="YOUR_PASSWORD";